name: CI

on:
  schedule:
    - cron: '53 8 5 * *'
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    container:
      image: practicalscheme/gauche
    steps:
      - uses: actions/checkout@v4
      - name: Setup package
        run: |
      - name: CI
        run: ./run-ci.sh
